name: skaffold-build-prerelease
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
jobs:
  pipeline:
    name: Skaffold Docker build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repo
      id: checkout
      uses: actions/checkout@v3
    - name: Set up Go Tools
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.21.0'
    - name: Build Executable
      run: |
        go build .
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "condor-launcher"
        prerelease: true
