name: golangci-lint
on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  call-workflow-passing-data:
    uses: cyverse-de/github-workflows/.github/workflows/golangci-lint.yml@v0.0.10
    with:
      go-version: 1.21
