name: Go

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  release:
    if: startsWith(github.ref, 'refs/tags/')
    name: cut release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
      
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true
          
      - name: Build
        run: go build .

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            condor-launcher
